# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1c6fe0efaad196c25ed3f530b14bcffa41c789816759ed6f1dcb5255c3c5cb2f20ed7f85836a661bcb7b572be3a725abc30b8c44769ba5fe374b43bfd23a8b7

test:
  secret_key_base: f7f5a3886a924a24e71d4892afebdad7b69eb0ed23d72fa4ea9cfa83fe3bd2b4c08777803436450d0121a716007eed0e5acbf1278044a2ebcae5d1216b26403a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
